/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BetZilla__factory } from "./BetZilla__factory";
export { BetzToken__factory } from "./BetzToken__factory";
